# Generated by Django 2.0.5 on 2018-10-26 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chs', '0002_auto_20181020_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='CoordinatorName',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
