# Generated by Django 2.0.5 on 2018-11-02 04:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0003_auto_20181026_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(choices=[('ICU/CC', 'ICU/CC'), ('ER', 'ER'), ('Med/Surg', 'Med/Surg'), ('OB', 'OB'), ('SICU', 'SICU'), ('OR', 'OR'), ('Peds', 'Peds'), ('PICU', 'PICU'), ('NICU', 'NICU'), ('Burn', 'Burn'), ('Mental Health', 'Mental Health'), ('Other', 'Other')], default='ICU/CC', max_length=50)),
                ('TotalBeds', models.IntegerField()),
                ('BedsUsed', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('HospitalID', models.IntegerField(primary_key=True, serialize=False)),
                ('HospitalName', models.CharField(max_length=100)),
                ('HospitalAddress', models.CharField(max_length=200)),
                ('HospitalCity', models.CharField(max_length=50)),
                ('HospitalState', models.CharField(max_length=50)),
                ('HospitalZipcode', models.CharField(max_length=10)),
                ('HospitalPhone', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='hospdepartment',
            name='HospitalName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HospDepartment', to='chs.Hospital'),
        ),
    ]
