# Generated by Django 2.0.5 on 2018-11-06 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0004_auto_20181101_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.IntegerField(primary_key=True, serialize=False)),
                ('PatientFirstName', models.CharField(max_length=100)),
                ('PatientLastName', models.CharField(max_length=100)),
                ('PatientDate_of_Birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('HospitalName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to='chs.Hospital')),
            ],
        ),
    ]
