# Generated by Django 2.0.5 on 2018-11-08 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0006_auto_20181106_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Condition_on_arrival',
            field=models.CharField(choices=[('good/fair', 'Good/Fair'), ('serious', 'Serious'), ('critical', 'Critical'), ('expired', 'Expired')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='Department',
            field=models.CharField(choices=[('ICU/CC', 'ICU/CC'), ('ER', 'ER'), ('Med/Surg', 'Med/Surg'), ('OB', 'OB'), ('SICU', 'SICU'), ('OR', 'OR'), ('Peds', 'Peds'), ('PICU', 'PICU'), ('NICU', 'NICU'), ('Burn', 'Burn'), ('Mental Health', 'Mental Health'), ('Other', 'Other')], default='ICU/CC', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='Disposition_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='Disposition_type',
            field=models.CharField(choices=[('To home', 'To home'), ('Other Hospital', 'Other Hospital'), ('SNF', 'SNF'), ('ICF', 'ICF')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='Triage_Tag_colour',
            field=models.CharField(choices=[('Green', 'Green'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Black', 'Black')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Date_of_Birth',
            field=models.DateTimeField(),
        ),
    ]
