# Generated by Django 2.0.5 on 2018-11-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0007_auto_20181108_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospdepartment',
            name='Department',
            field=models.CharField(choices=[('ICU/CC', 'ICU/CC'), ('ER', 'ER'), ('Med/Surg', 'Med/Surg'), ('OB', 'OB'), ('SICU', 'SICU'), ('Neg_Pres_Iso', 'Neg Pres/Iso'), ('OR', 'OR'), ('Peds', 'Peds'), ('PICU', 'PICU'), ('NICU', 'NICU'), ('Burn', 'Burn'), ('Mental Health', 'Mental Health'), ('Other', 'Other')], default='ICU/CC', max_length=50),
        ),
    ]
