# Generated by Django 2.0 on 2018-11-10 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0008_auto_20181109_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Date_of_Birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
