# Generated by Django 2.0.5 on 2018-11-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0009_auto_20181108_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospdepartment',
            name='AvailableBeds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
