# Generated by Django 2.0 on 2018-11-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0009_auto_20181110_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Date_of_Birth',
            field=models.DateField(null=True),
        ),
    ]
