# Generated by Django 2.0 on 2018-11-10 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0010_auto_20181110_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Date_of_Birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
