# Generated by Django 2.0.5 on 2018-11-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0010_hospdepartment_availablebeds'),
        ('chs', '0011_auto_20181110_1741'),
    ]

    operations = [
    ]
