# Generated by Django 2.0.5 on 2018-11-12 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0012_merge_20181110_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Kin_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='Relationship_To_Victim',
            field=models.CharField(choices=[('Wife', 'Wife'), ('Mother', 'Mother'), ('Father', 'Father'), ('Husband', 'Husband'), ('Daughter', 'Daughter'), ('Son', 'Son'), ('Others', 'Others')], default='Wife', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='Room_No_If_Admitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='Time_of_Death',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Injury_type',
            field=models.CharField(choices=[('Strains/Sprains', 'Strains/Sprains'), ('Burns', 'Burns'), ('Abrasions', 'Abrasions'), ('Internal Injuries', 'Internal Injuries'), ('Fractures', 'Fractures'), ('Respiratory Conditions', 'Respiratory Conditions'), ('Others', 'Others')], default='', max_length=10),
        ),
    ]
