# Generated by Django 2.0 on 2018-11-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chs', '0014_auto_20181112_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='EventID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
